### ISSUE TITLE
stdout getting spammed by a repeated "eth_getFilterLogs"

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/keeper-contracts#133]
Note: I'm not sure if this is an issue for this repo (keeper-contracts) or the docker-images repo.

My software versions:
* Ubuntu 18.04 (64-bit)
* Docker version 18.06.1-ce (latest release at time of writing)
* docker-compose version 1.22.0 (latest release at time of writing)

Today when I ran the latest oceanprotocol/keeper-contracts container by using
```bash
./start_ocean.sh --latest
```
from the [oceanprotocol/docker-images repo](https://github.com/oceanprotocol/docker-images), stdout ends up getting spammed something like this but going forever:
```bash
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
keeper-contracts_1  | eth_getFilterLogs
```

I think this might be a [ganache-cli](https://github.com/trufflesuite/ganache-cli) thing.

eth_getFilterLogs is part of [the Ethereum JSON RPC API](https://github.com/ethereum/wiki/wiki/JSON-RPC).

**Comment by kremalicious** [comment]
this! +1

Would love to know if there's a way for ganache to be less verbose

**Comment by ttmc** [comment]
Some notes: It doesn't happen if you just run the keeper-contracts container by itself. It arises out of some interaction or connection between the keeper-contacts container and a provider container.

**Comment by H34D** [comment]
Thats a know issue with `provider` being to aggressive on polling blockchain events. @eruizgar91

**Comment by H34D** [comment]
please file an issue in https://github.com/oceanprotocol/aquarius, closing this
