### ISSUE TITLE
Security Analysis for ServiceAgreement.sol

### ISSUE THREAD

**Issue by aabdulwahed** [oceanprotocol/keeper-contracts#134]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository.

## Expected Behavior

Minimal security warning in service level agreement contract

## Current Behavior

It is working as usual

## Failure Information (for bugs)
```
# Analysis results for contracts/service_agreement/ServiceAgreement.sol

## Integer Overflow

- Type: Warning
- Contract: ServiceAgreement
- Function name: `setupAgreementTemplate(address[],bytes4[],uint256[],bytes32)`
- PC address: 2526

### Description

A possible integer overflow exists in the function `setupAgreementTemplate(address[],bytes4[],uint256[],bytes32)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
In file: contracts/service_agreement/ServiceAgreement.sol:76

### Code

```
templates[templateId] = ServiceAgreementTemplate(true, msg.sender, new bytes32[](0), dependencies)
```

## Exception state

- Type: Informational
- Contract: ServiceAgreement
- Function name: `hasUnfulfilledDependencies(bytes32,bytes32)`
- PC address: 4851

### Description

A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking.
In file: contracts/service_agreement/ServiceAgreement.sol:175

### Code

```
templates[agreements[serviceId].templateId].dependencies[conditionKeyToIndex[condition]]
```

## Integer Overflow

- Type: Warning
- Contract: ServiceAgreement
- Function name: `setupAgreementTemplate(address[],bytes4[],uint256[],bytes32)`
- PC address: 9342

### Description

A possible integer overflow exists in the function `setupAgreementTemplate(address[],bytes4[],uint256[],bytes32)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
In file: contracts/service_agreement/ServiceAgreement.sol:3


## Integer Overflow

- Type: Warning
- Contract: ServiceAgreement
- Function name: `setupAgreementTemplate(address[],bytes4[],uint256[],bytes32)`
- PC address: 9344

### Description

A possible integer overflow exists in the function `setupAgreementTemplate(address[],bytes4[],uint256[],bytes32)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
In file: contracts/service_agreement/ServiceAgreement.sol:3

```

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Step to Reproduce the problem

```
myth -xo markdown contracts/service_agreement/ServiceAgreement.sol --max-depth 12
```

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: x.x.x
* Python: x.x
* Solidity: x.x.x
* JavaScript: x.x.x
* Node: x.x.x
* OS: macOS/linux/win

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by H34D** [comment]
closed with: https://github.com/oceanprotocol/keeper-contracts/pull/143

**Comment by H34D** [comment]
sorry wrong issue

**Comment by aabdulwahed** [comment]
will be handled in this issue #245
