### ISSUE TITLE
./artifacts folder is out of sync with the current truffle build

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/keeper-contracts#145]
## Expected Behavior

Not all of the contracts are being installed in the pypi package, because the list of contracts in the _artifacts_ folder is not the same as the list of contracts in the _./build/contracts_ after a ```truffle compile```

see setup.py
```python
data_files = []
directories = glob('artifacts/*.json')
for directory in directories:
    files = glob(directory+'*')
    print("Contract artifact found:",directory, files)
    data_files.append((directory, files))
```

### Possible Solution

I think that the following contracts should be available in the _artifacts_ folder:

1. AccessConditions.json
1. OceanMarket.json	
1. DIDRegistry.json	
1. OceanAuth.json		
1. OceanToken.json		
1. PaymentConditions.json	
1. ServiceAgreement.json

**Comment by H34D** [comment]
touches https://github.com/oceanprotocol/keeper-contracts/issues/147

**Comment by jcortejoso** [comment]
Currently the same contracts are packaged in all the packages. I think we can close the issue.
