### ISSUE TITLE
Update travis to deploy stable tag for python components

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/keeper-contracts#147]
## Expected Behavior

For trilobite development in squid-py etc., we currently require:
1. All contract .json ABI files in the artifacts updated to latest .sol code 
1. Deployed PyPI package containing above .JSON files
1. Docker image deployed

All the above should be tagged with the same version number. 

## Current Behavior

- Missing .json
- No pypi deploy
- Inconsistent tags

### Possible Solution

Update travis?

**Comment by H34D** [comment]
Pypi deployment should have been done here: https://github.com/oceanprotocol/keeper-contracts/issues/72

There is still a list of things to clean up this repo: https://github.com/oceanprotocol/keeper-contracts/issues/65

**Comment by H34D** [comment]
touches https://github.com/oceanprotocol/keeper-contracts/issues/145

**Comment by jcortejoso** [comment]
Hi @MarcusJones, what do you refer about with _Inconsistent tags_? For docker images the tags for versions are the same as github tag (i.e.: v0.3.2). 
Apart from that the PyPi package should be generated next time a new tag is pushed to github.

**Comment by jcortejoso** [comment]
Currently for packaging artifacts (pypi, npm and nexus) we use a version following the standard of semantic versioning (https://github.com/semver/semver), `x.y.z`. For git tags and docker images we have the same version with a `v` prefix, `vx.y.z`. This is a common pattern to contextualize that it is a version in spaces where another versioning system can be used (as git tags). In fact the Semantic Versioning Standard itself use this pattern (https://github.com/semver/semver/tree/v2.0.0).

We can think if we want to use the `v` prefix or not, but apart from that versions are currently  synced in CI deployments.

**Comment by H34D** [comment]
> Currently for packaging artifacts (pypi, npm and nexus) we use a version following the standard of semantic versioning (https://github.com/semver/semver), `x.y.z`. For git tags and docker images we have the same version with a `v` prefix, `vx.y.z`. This is a common pattern to contextualize that it is a reference to a version, in spaces where another kind of 'annotations' can be used (as git tags). In fact the Semantic Versioning Standard itself use this pattern (https://github.com/semver/semver/tree/v2.0.0).
> 
> We can think if we want to use the `v` prefix or not, but apart from that versions are currently synced in CI deployments.

releasing and versioning works quite nicely now. can we close this @jcortejoso @MarcusJones ?

**Comment by H34D** [comment]
related #184
