### ISSUE TITLE
Testnet deployment transactions do not show up at stated address.

### ISSUE THREAD

**Issue by theoturner** [oceanprotocol/keeper-contracts#170]
## Expected Behavior

According to the readme, testnet deployment should show up at https://kovan.etherscan.io/address/0x2c0d5f47374b130ee398f4c34dbe8168824a8616.

## Current Behavior

Contracts are deployed from the local address. Example: https://kovan.etherscan.io/address/0x2b8901ce7d7a9ee839a8cec14551014e9c27e10c.
INFURA_TOKEN and KOVAN_NMEMORIC are set and npm run migrate:kovan completes successfully.

**Comment by H34D** [comment]
well, you need the right mnemonic phrase for this address.

**Comment by H34D** [comment]
addressed in: #179

**Comment by H34D** [comment]
fixed with #179

**Comment by theoturner** [comment]
I can now not migrate to Kovan. I get the error `"Migrations" -- Unknown address - unable to sign transaction for this address: "0x2c0d5f47374b130ee398f4c34dbe8168824a8616".` whether I set INFURA_TOKEN and KOVAN_NMEMORIC or not.
