### ISSUE TITLE
Tagged contract artifacts 

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/keeper-contracts#177]
Keeper contract artifacts .json files are created with the `address` field. Can we also add the version (i.e. `v0.3.19` tag into the .json file? This would ensure at least that if I run a tagged docker image of k-c,  I can check that my artifacts are in-sync with the deployed versions! 

Related to #147

**Comment by H34D** [comment]
closed in favor of #184

**Comment by H34D** [comment]
@MarcusJones please approve PR #195 if it meets your requirements
