### ISSUE TITLE
Migrate to solidity 0.5.0

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#181]
# Description

Solidity 0.5.0 was released and is a security release. It has a lot of breaking changes. https://solidity.readthedocs.io/en/latest/050-breaking-changes.html

This is post trilobite.

**Comment by aabdulwahed** [comment]
I have reported an issue in ZOS lib. Keep you notified when they migrate to the new version.

**Comment by aaitor** [comment]
Before applying this change, needs to be analyzed if the web3 libraries (py, js, java) in use don't have any compatibility issue.

**Comment by H34D** [comment]
closes with #288

**Comment by H34D** [comment]
done with v0.7
