### ISSUE TITLE
ExecuteAgreement doesn't throw on invalid signature

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/keeper-contracts#208]
# Prerequisites

## Expected Behavior

Throw on InvalidSignature
https://github.com/oceanprotocol/keeper-contracts/blob/develop/contracts/SLA/ServiceAgreement.sol#L179

## Current Behavior

Doesn't throw and sets `state=False` in event. `receipt.status` is `True`, indicating success

**Comment by H34D** [comment]
changing this is a breaking change and will break `squid-js` postponed.

**Comment by aabdulwahed** [comment]
@H34D please connect the updates/PRs you are working on to this issue for better tracking :)

**Comment by H34D** [comment]
well #220 is the one, thanks for hinting

**Comment by H34D** [comment]
also #218 tries to revert back to a compatible state with the rest
