### ISSUE TITLE
Remove value type in did registry

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/keeper-contracts#212]
## Expected Behavior
It suppose that there is only a type of did registry possible that link the did with the aquarius url to allow the resolving mechanism.

## Current Behaviour
When you have to register a did you have to specify a value type that is making difficult the resolving in the different squid implementations and could be a point of failure.
https://github.com/oceanprotocol/keeper-contracts/blob/develop/contracts/didregistry/DIDRegistry.sol

**Comment by aabdulwahed** [comment]
@eruizgar91  can you provide an example for this issue ?

**Comment by eruizgar91** [comment]
What I mean is that now we are adding to the resolver a field called type to specify if we are registering a did, a did_ref, an url or a ddo. But this is not given as so much value, because at the end we are only going to be registering the url to resolve a did and get the ddo associated. I think that it would be simple if we don't use this value.

**Comment by aabdulwahed** [comment]
closes with #285
