### ISSUE TITLE
Review and update the Compute Conditions to be aligned with OEP-12

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#228]
**This user story only should be started after the [OEP-12](https://github.com/oceanprotocol/OEPs/pull/118) approval**

The OEP-12 introduce the complete flow of the cloud computing template. This is already implemented as conditions in the keeper-contracts. After the OEP-12 review and approval, it would be necessary to review the existing implementation of the Compute Conditions to reconciliate with the definition.

**Comment by H34D** [comment]
is this still up to date? @aaitor

**Comment by aaitor** [comment]
This is post v1.0

**Comment by H34D** [comment]
The compute conditions have not made it through the large January refactoring and need to be ported. I found the most recent version in keeper `v0.5.x` tags:

https://github.com/oceanprotocol/keeper-contracts/blob/v0.5.0/contracts/SLA/ComputeConditions.sol

**Comment by H34D** [comment]
closed in favour of #581
