### ISSUE TITLE
Link Broken in Readme

### ISSUE THREAD

**Issue by aj07** [oceanprotocol/keeper-contracts#230]
While going through the readme section i figured out that in section https://github.com/oceanprotocol/keeper-contracts#documentation  , link of **Packaging of libraries** is broken.

**Comment by aabdulwahed** [comment]
@aj07  I think this part should be removed from the readme file and only refer to https://docs.oceanprotocol.com

**Comment by H34D** [comment]
Either fix the file `packaging.md` or remove it and link to `docs` please see: https://github.com/oceanprotocol/keeper-contracts/pull/246#discussion_r245571750

**Comment by aj07** [comment]
Done.
