### ISSUE TITLE
Removing duplicates in AccessConditions.sol

### ISSUE THREAD

**Issue by aabdulwahed** [oceanprotocol/keeper-contracts#237]
### Problem
There is a duplicate in the `AccessConditions.sol` as follows:
- `grantAccess( bytes32 agreementId, bytes32 assetId, bytes32 documentKeyId)` 
takes two arguments (assetId and documentKeyId) which they are referring to the same Id (DID).

### Recommendation
- Remove the duplicates and use only one variable
- I would recommend to use `documentKeyId` that refers to DID in order to be consistent with the Parity secret store documentation.

**Comment by H34D** [comment]
I like it, i also added an interface for secret store: https://github.com/oceanprotocol/keeper-contracts/pull/220/commits/d384c5a2d350ed65dc4ab1bcd5902d9a787d979c
