### ISSUE TITLE
Implement Mint/Burn to support the Different requirements regarding token distribution

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#243]
## Description

Right now we have the following approach to get Tokens:

`OceanToken` is deployed to Blockchain.
`OceanMarket` is deployed to Blockchain.
`OceanMarket` registers as receiver of all tokens to `OceanToken`
`OceanToken` mints its `TOTAL_SUPPLY` to `OceanMarket` Address
Leaving `OceanMarket` holding all the Tokens.

Before Payment we request tokens from the `OceanMarket` with `requestTokens` and approve them on `OceanToken` with `OceanToken.approve(amount)`. 

We have the following challenges:
1. Token Bridge / Vortext / Hot Swapping - Based on events we need to Mint or Burn tokens (eg. Cross Blockchain transfer or Hot Swap to `Drop`'s)
2. Migrate/Exchange from `BountyOceanToken` to real `OceanToken`
3. Initial Token distribution - We need to get the tokens to the investors
4. Airdrops - We need to Airdrop small amounts of tokens
5. Potential: Staking on we. - Similar to Swapping (but with Bonding curves)
6. Token or Network rewards - Distribute tokens for done tasks

Mostly described here: https://github.com/oceanprotocol/dev-ocean/blob/725c9d495af5768e4d2e46e65530f4dff5887a50/doc/refactoring_design.md#21-ocean-token

## Approach

Add Mint / Burn functionality and add Authorised Minters

![untitled diagram](https://user-images.githubusercontent.com/13647606/50685584-0e806380-101a-11e9-8020-b2634308eab1.png)

With this design it's only Possible to mint `OceanToken` if you either have deployed the `OceanToken` contract or if the owner has called the `addMinter` method on the `OceanToken` contract.

**Comment by diminator** [comment]
Minting Ocean token would be very hard to control: How do one ensure there is no over or undermint?

One idea is to have the initial `mint` happening only at TGE. All the rest are dispensers or swappers.
A token bridge would not `mint` Ocean Token - it would `lock` and `unlock` (escrow style)

**Comment by H34D** [comment]
> A token bridge would not `mint` Ocean Token - it would `lock` and `unlock` (escrow style)

but why, minting them on the one side and burn them on the other side is much clearer.

**Comment by H34D** [comment]
also you cannot undermint because of: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/63ce358f30d71e5af5f70bbd4db7daea379b7c9b/contracts/token/ERC20/ERC20.sol#L168

**Comment by diminator** [comment]
> but why, minting them on the one side and burn them on the other side is much clearer. Also you can replace the bridge at any time without need to get the tokens out before.

Well, this requires us to define the `TOTAL_TOKEN_SUPPLY` either as:
- invariant across all chains: `sum(tokens_chain_1, ..., tokens_chain_N) = TOTAL_TOKEN_SUPPLY`
- invariant per chain: `tokens_chain_1 = ... = tokens_chain_N = TOTAL_TOKEN_SUPPLY`

**Comment by diminator** [comment]
Another requirement is to preserve the token allocation relative to the `TOTAL_TOKEN_SUPPLY`:
- % network rewards: planned release schedule
- % presale: minted and assigned on TGE
- % community: spot release

**Comment by aabdulwahed** [comment]
>% network rewards: planned/governed release schedule
% pre-sale: minted and assigned on TGE
% community: spot release
% other: miscellaneous

@H34D an additional point to what @diminator  has said, for each type we need to define who is illegible to mint these tokens.

**Comment by H34D** [comment]
> @H34D an additional point to what @diminator has said, for each type we need to define who is illegible to mint these tokens.

of course, we could have different contracts to mint those tokens with this concept

**Comment by H34D** [comment]
Good point:

we can use the RBAC from open zeppelin described here:

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/63ce358f30d71e5af5f70bbd4db7daea379b7c9b/contracts/token/ERC20/ERC20Mintable.sol#L10
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/63ce358f30d71e5af5f70bbd4db7daea379b7c9b/contracts/token/ERC20/ERC20Mintable.sol#L17
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/63ce358f30d71e5af5f70bbd4db7daea379b7c9b/contracts/access/roles/MinterRole.sol#L17
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/63ce358f30d71e5af5f70bbd4db7daea379b7c9b/contracts/access/roles/MinterRole.sol#L26

**Comment by H34D** [comment]
> Well, this requires us to define the `TOTAL_TOKEN_SUPPLY` either as:
> 
> * invariant across all chains: `sum(tokens_chain_1, ..., tokens_chain_N) = TOTAL_TOKEN_SUPPLY`
> * invariant per chain: `tokens_chain_1 = ... = tokens_chain_N = TOTAL_TOKEN_SUPPLY`

added cap back: https://github.com/oceanprotocol/keeper-contracts/pull/244/commits/e0549b7d1cfb82a82c52957cf435e45d5fd5ac51

**Comment by H34D** [comment]
resolved with #244
