### ISSUE TITLE
Top-10 vector attacks code review

### ISSUE THREAD

**Issue by aabdulwahed** [oceanprotocol/keeper-contracts#245]
Keeper contracts should at least pass the top 10 vector attacks:

### References:
- [SWC Registry: Smart Contract Weakness Classification and Test Cases](https://smartcontractsecurity.github.io/SWC-registry/)
- [Decentralized Application Security Project (or DASP) Top 10 of 2018](https://www.dasp.co/)
- [trailofbits/not-so-smart-contracts](https://github.com/trailofbits/not-so-smart-contracts)
- [Classification of smart contract vulnerabilities](https://github.com/smartdec/classification)
- [Comprehensive list of known attack vectors and common anti-patterns](https://blog.sigmaprime.io/solidity-security.html)

**Comment by aj07** [comment]
An important link to go though regarding attack vector: 
https://blog.sigmaprime.io/solidity-security.html

**Comment by aabdulwahed** [comment]
It is already tracked in Travis CI.
