### ISSUE TITLE
Migrate Mythril to 0.19.x+

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#262]
Right now we are using an outdated version of mythril because it is the only version that is running and outputting proper results in our context. See https://github.com/oceanprotocol/keeper-contracts/blob/9a9edb5473843f5b628c7916785d83beeacee787/requirements_dev.txt#L18

**Comment by aabdulwahed** [comment]
closes with #284

**Comment by H34D** [comment]
closes with #380
