### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#268]
The documentation under https://github.com/oceanprotocol/keeper-contracts/tree/develop/doc is quite old. It needs rework.

**Comment by ttmc** [comment]
The page https://github.com/oceanprotocol/dev-ocean/blob/master/doc/development/contract-governance.md lives over in the dev-ocean repo but it's out-of-date and it would make more sense if it was in this repo. In fact, there's already the page`doc/upgrades.md` in this repo.

Suggestion: Update https://github.com/oceanprotocol/dev-ocean/blob/master/doc/development/contract-governance.md to point to `doc/upgrades.md` in this repo. Also decide what to do about the **Structured Storage** and the **Unstructured Storage** sections in the old page.

**Comment by H34D** [comment]
#348
