### ISSUE TITLE
Rewrite contract deploy script in node

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#274]
Right now this bash script is having some issues:

* detecting the right accounts from the node is hard
* wallet management (with the multisig) is hard
* bad dependency management (jq is required which is not there on all systems #273)

https://github.com/oceanprotocol/keeper-contracts/blob/develop/scripts/deployContracts.sh

**Comment by aabdulwahed** [comment]
closes with [#282](https://github.com/oceanprotocol/keeper-contracts/pull/282)

**Comment by H34D** [comment]
> closes with [#282](https://github.com/oceanprotocol/keeper-contracts/pull/282)

yep, thanks
