### ISSUE TITLE
requestToken fails in squid-py using keeper-contracts v0.6.9

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/keeper-contracts#281]
Calling `requestTokens` on the `Dispenser` contract fails for no apparent reason.

No events were emitted from this function and strangely no revert either.

To reproduce:
* Run barge using this command:
`KEEPER_VERSION=v0.6.9_fix bash -x start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node --force-pull`
* Checkout the `feature/#254-update-to-keeper-0.6` squid-py branch and run `test_token_request` test in test_ocean.py.

**Comment by H34D** [comment]
`Dispenser` is not jet registered in the `OceanToken` as a minter. This is an after migration step like deploying the ServiceAgreementTemplate is. Good catch thanks.

**Comment by H34D** [comment]
closes with #282
