### ISSUE TITLE
Bug in electRRKVerifiers function of FitchainConditions

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#287]
`i` is undefined in line 572 should be `j` i guess?

https://github.com/oceanprotocol/keeper-contracts/blob/f062dec49e68fbead045c7d4f8f4dc594cc46acc/contracts/SEA/FitchainConditions.sol#L560-L580

**Comment by aabdulwahed** [comment]
closes with #288

**Comment by H34D** [comment]
> Thanks @H34D ... closes with #288

postponed to `release/v0.7`

**Comment by H34D** [comment]
there is no fitchain condition anymore with v0.7
