### ISSUE TITLE
Add ComputeConditions to code coverage again

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#289]
solidity-coverage has problems supporting solidity 0.5.x as seen here: https://github.com/sc-forks/solidity-coverage/pull/311
because of that i excluded `ComputeConditions` from code coverage (temporary): https://github.com/oceanprotocol/keeper-contracts/commit/ceeeab0628392d8afb220cc0997d03dba0d0db28

**Comment by H34D** [comment]
Because it is the only contract that has a `bytes` parameter on a function that is declared as `external`: https://github.com/oceanprotocol/keeper-contracts/blob/ceeeab0628392d8afb220cc0997d03dba0d0db28/contracts/SEA/ComputeConditions.sol#L102

If the following is the case the parameter has to have the storage type `calldata` which is unknown by current solcover Version.

**Comment by aabdulwahed** [comment]
so it happens only in case of `external` but it works for `public`?

https://github.com/oceanprotocol/keeper-contracts/blob/develop/contracts/SEA/Common.sol#L31-L35

**Comment by H34D** [comment]
right because it can be `memory` instead of `calldata` i assumed that it is external by intention.

**Comment by aabdulwahed** [comment]
It is okay to change the visibility of the function to public as there is no risk of change it from `external` to `public`.

**Comment by H34D** [comment]
solved with v0.7
