### ISSUE TITLE
Improve Travis job duration

### ISSUE THREAD

**Issue by jcortejoso** [oceanprotocol/keeper-contracts#292]
## Current Behavior

Currently the Travis job usually takes longer than 1 hour to complete, which causes that some jobs get queued for long time where there some pushes close in time in `keeper-contracts`.

## Expected Behavior

Optimize the time `keeper-contracts` travis job longs. We should think which part can be run daily (security reports for example) or as custom build, and reduce the job in the main job to one where we comfortable with the tests but also with the duration.

**Comment by H34D** [comment]
Possible solutions:

- exclude upgradability tests from collecting code coverage
- run code coverage nightly
- run security checks nightly
