### ISSUE TITLE
Artifacts addresses do not match the contract addresse initialized during deployment.

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/keeper-contracts#298]
Steps:
* ganache-cli
* npm run migrate (in keeper-contracts)
* Copy artifacts to `squid-py/artifacts`
* In squid-py, run `ocean_test.test_token_request`
* requestTokens will fail because the contract addresses in artifacts belong to the original contacts whereas the actual contrats that were initialized during deployment are proxy contracts in zeppelin os

Possible solution: 
When exporting the artifacts, use the proxy contracts addresses instead of the original addresses.

**Comment by H34D** [comment]
closes with #295
