### ISSUE TITLE
Adaptation of OceanToken.sol for Network Release

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#304]
# OceanToken.sol

When these tasks are done we should have an ERC20 token with a cap and correct Owner and Minter roles. Tasks:

- [x] Setup the correct amount of the cap: 1,410,000,000 (1.41B, 1.41*10E9)
- [x] Choose the right ticker (OCEAN)
- [x] Setup the initial Minter. Validation!!. Separate the Deployer from the Minter. Currently, the user who is deploying the contract is the Minter registered in the system
- [x] Define the flow to add/renounce Minters is correct. This needs to be battle tested.

Implements #303

**Comment by H34D** [comment]
Right now we have implemented the OceanToken to have 18 digits for compliance reason, shall we keep it this way or change it?

**Comment by H34D** [comment]
closes with #332
