### ISSUE TITLE
Adaptation of Dispenser.sol for Network release

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#305]
#### Dispenser.sol

- [x] Create an abstraction of the Dispenser class
- [x] Create the logic for setting up the MAX_MINT_AMOUNT. As well the validation of that.
- [x] UT + E2E testing of the complete flow. We have to be able to register/renounce Dispenser and validate corner case scenarios. Taking into account we are going to need to add in the coming future additional Dispensers (NetworkRewardDispenser).
- [x] Add onlyOwner modifier to functions that can set the config attributes of dispenser

Implements #303

**Comment by H34D** [comment]
closes with #332
