### ISSUE TITLE
Review and adaptation of MultiSigWallet.sol for Network launch

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#307]
#### MultiSigWallet.sol

Once this is done we should be able to validate that MultiSigWallet only allows to the proper owners to operate in the system. Tasks:

- [x] Upgrade the current version of MultiSigWallet contract (Gnosis)
- [x] Validate the current contract
- [x] Set the roles of the owners that are initialized
- [x] Validate the way of adding/removing owners is the logic we want
- [x] Set the threshold. The number of signatures required. And validate the update of this value.
- [x] Battle tested submit, confirm, revoke and executeTransaction methods
- [x] E2E test in conjunction with the dispenser

Implements #303

**Comment by H34D** [comment]
We should go for: https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol

This requires solidity 0.5

**Comment by H34D** [comment]
Closes with: https://github.com/oceanprotocol/keeper-contracts/pull/322
