### ISSUE TITLE
Integration of Slither static analysis framework as part of the CI flow

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#336]
https://github.com/trailofbits/slither

Slither is a Solidity static analysis framework written in Python 3. It runs a suite of vulnerability detectors, prints visual information about contract details, and provides an API to easily write custom analyses. Slither enables developers to find vulnerabilities, enhance their code comphrehension, and quickly prototype custom analyses.

**Comment by H34D** [comment]
report is here: https://github.com/oceanprotocol/keeper-contracts-security-reports/blob/master/develop_slitherReport.txt
