### ISSUE TITLE
Adding missing Events

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#338]
Before finalize the keeper v0.7 refactor would be necessary to add again the missing Events. Requirements:

* The events should preserve the original OEP11 flow
* The event names should be as similar as possible to the previous events (keeper v0.6). Some of those could require renaming for consistency with the new version (document).
* The events should include similar parameters if possible. Some parameters could change for consistency (document). 
* The events should include the `indexed` attributes as in previous versions

All the breaking changes must be documented in the CHANGELOG.md of the 0.7 version

**Comment by aaitor** [comment]
Please @ssallam , as we discussed can you take a look at it please?

**Comment by H34D** [comment]
closes with #384
