### ISSUE TITLE
EpochLibrary unique create

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/keeper-contracts#353]
from @gongf05 

"create" function does not check the same "bytes32 _id" exist or not. It may overwrite existing epoch record accidentally.

**Comment by aabdulwahed** [comment]
@diminator @gongf05 I think libraries does not have access for the storage (including they don't have a storage). So when you say `create` you mean in `ConditionStoreManager.sol` or `EpochLibrary`. Any checks for storage should be outside of the library. Libraries should be storage agnostic.

**Comment by aabdulwahed** [comment]
Fixed [here](https://github.com/oceanprotocol/keeper-contracts/blob/develop/contracts/libraries/EpochLibrary.sol#L35)
