### ISSUE TITLE
EscrowAgreement integration test correct receiver

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/keeper-contracts#383]
sender: consumer
receiver: publisher

make sure the following tx's are coming from `receiver`
`await didRegistry.registerAttribute(agreement.did, checksum, url)`
`await accessSecretStoreCondition.fulfill(agreementId, agreement.did, receiver)`

**Comment by H34D** [comment]
closes with #389

**Comment by H34D** [comment]
not sure if this really solves it @diminator @aabdulwahed, can you please confirm?

**Comment by aabdulwahed** [comment]
sure, I will
