### ISSUE TITLE
Missing events in keeper v0.8

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/keeper-contracts#386]
Adding a list of missing events the following files:

- [ ] SignCondition.sol - Events (`Fulfilled`)
- [ ] HashLockCondition.sol - Events (`Fulfilled`)
- [ ] TemplateStoreManager.sol - Events (`Proposed`, `Approved`, `Revoked`)

**Comment by aabdulwahed** [comment]
@diminator , @ssallam can you review this issue ?

**Comment by 0x3bfc** [comment]
@aaitor suggested to move all events to single name with a filter.
