### ISSUE TITLE
Deploy some templates for development purposes

### ISSUE THREAD

**Issue by Pedro-vk** [oceanprotocol/keeper-contracts#400]
Could be a good idea to deploy some templates like `EscrowAccessSecretStoreTemplate` for development purposes.

**Comment by ssallam** [comment]
The template is `deployed`, what is necessary is to have it `approved` as part of the keeper-contracts deployment process. And for now, we only need the one template `
EscrowAccessSecretStoreTemplate`.

**Comment by H34D** [comment]
duplicate of #264
