### ISSUE TITLE
As user I would like to know how and when I can use the Ocean Dispenser

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#432]
# Prerequisites

The Ocean Dispenser Smart Contract allows users to request Ocean tokens. Obviously, this is a functionality quite useful in local environments and testnets but never can be deployed to a live environment where Ocean Tokens are having real value.

## Expected Behavior

In the scope of this user story it would be necessary:
- [ ] Document (docs website) how the users can use this functionality and where (spree, nile)
- [x] Implement the checks in the deployment script removing the possibility of install the Dispenser Smart Contract in networks different to spree, nile or kovan

**Comment by H34D** [comment]
By default the `Dispenser` contract is deployed. We can define which contracts are deployed in the deployment to `pacific` here:

https://github.com/oceanprotocol/keeper-contracts/blob/603367531c24dc1259cc075c2f1a7d46d4feeff7/scripts/deploy/contracts/contracts.json#L1-L14

**Comment by ttmc** [comment]
> By default the Dispenser contract is deployed.

If we were to follow the philosophy of having secure defaults, then the default would be to not deploy the Dispenser contract (i.e. remove it from the array in `contracts.json`). Then there could be some code like the following in the deployment scripts:

_if NETWORK is one of the test networks, then append "Dispenser" to the array of contracts to deploy_

**Comment by H34D** [comment]
> > By default the Dispenser contract is deployed.
> 
> If we were to follow the philosophy of having secure defaults, then the default would be to not deploy the Dispenser contract (i.e. remove it from the array in `contracts.json`). Then there could be some code like the following in the deployment scripts:
> 
> _if NETWORK is one of the test networks, then append "Dispenser" to the array of contracts to deploy_

good point

**Comment by H34D** [comment]
Made deployment of `Dispenser` a special case / optional in: #477

**Comment by H34D** [comment]
closed with #477
