### ISSUE TITLE
Support asset/agreement provider in addition to the asset owner

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/keeper-contracts#434]
The current SEAs in keeper-contracts restricts the fulfillment of access condition to the asset publisher. When running the commons/public marketplace/brizo, it can be responsible for serving agreements for different assets published by different accounts.

Solution: Modify the SEAs and DIDRegistry to support asset providers that can create and fulfill service agreements of assets owned by other accounts
* DIDRegistry:
  * Associate did with 0 or more provider addresses
  * Include provider's list in DID registery event (not indexed)
  * Add functions to `Add` and `Remove` provider
  * Add functions to check if address is a provider of DID
  * Only DID owner (publisher) is allowed to Add/Remove providers
* EscrowAccessSecretStoreTemplate.AgreementCreated event:
  * Use `sender` as `_accessProvider` , make sure this is `indexed`, can remove `indexed` from the `_accessConsumer` 
```
    event AgreementCreated(
        bytes32 indexed _agreementId,
        bytes32 indexed _did,
        address indexed _accessConsumer,
        address _accessProvider,
        uint[]  _timeLocks,
        uint[]  _timeOuts
    );
```

* EscrowAccessSecretStoreTemplate.createAgreement method:
  * Set the `sender` as `accessProvider` instead of the did owner

```
        agreementData.agreementDataItems[_id]
            .accessProvider = didRegistry.getDIDOwner(_did);
```

in the above, replace `didRegistry.getDIDOwner(_did)` with `msg.sender` after verifying that sender is a provider of DID, if not, default to did owner (we want to allow consumer to create the agreement). 
Note: it maybe best to include `provider` in the `createAgreement` arguments explicitly

* AccessSecretStoreCondition.fulfill:
  * Allow did owner or any of the registered did providers to fulfill this condition
* EscrowReward(Condition):
  * Use did owner address in creating the condition id
  * In the future, we can allow multiple reward receivers, i.e. did owner and provider

**Comment by H34D** [comment]
is this fixed @aaitor @ssallam ?

**Comment by aaitor** [comment]
yep, it can be closed
