### ISSUE TITLE
Upgrade Echidna to support solidity 0.5.7

### ISSUE THREAD

**Issue by aabdulwahed** [oceanprotocol/keeper-contracts#451]
Currently, the [travis job](https://travis-ci.com/oceanprotocol/keeper-contracts/builds/104585842#L2206) fails because the existing echinda tool does not support the 0.5.6/0.5.7.

**Comment by H34D** [comment]
This docker repo has to be configured properly:

https://cloud.docker.com/u/oceanprotocol/repository/docker/oceanprotocol/echidna/builds

**Comment by aabdulwahed** [comment]
@H34D there is an issue with Echidna and solc 0.5.7. The issue was reported yesterday. I'll downgrade the Echidna to use 0.5.6 and see how it goes.
