### ISSUE TITLE
npm install fails on Node 10+

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/keeper-contracts#46]
### Node.js v10

Tried installing latest `@oceanprotocol/keeper-contracts` version from npm (v0.0.17) on Node v10.8.0 but installation fails on `ursa` build step:

```bash
> ursa@0.9.4 install /Users/matthias/Code/oceanprotocol/pleuston/node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:389:13: error: member access into incomplete type 'RSA'

...
```

Seems like a known problem, a fix has been merged into `master` https://github.com/JoshKaufman/ursa/pull/169 but no new `ursa` version has been published to npm.

We could do the following in `package.json` to simply grab the `master` branch:

```json
"dependencies": {
  "ursa": "github:JoshKaufman/ursa"
}
```

### Node.js v8+

**Update**: Node v8 & v9 installation works now with v0.0.23

When using v8 & v9, installation of v0.0.17 fails on `truffle install`:

```bash
> @oceanprotocol/keeper-contracts@0.0.17 install /Users/matthias/Code/oceanprotocol/pleuston/node_modules/@oceanprotocol/keeper-contracts
> truffle install

TypeError: Cannot convert undefined or null to object
```

<img width="230" alt="screen shot 2018-08-09 at 11 50 23" src="https://user-images.githubusercontent.com/90316/43891818-904a3176-9bca-11e8-8dec-e1f9e0bfd1eb.png">

**Comment by H34D** [comment]
fixed with: https://github.com/oceanprotocol/keeper-contracts/pull/175
