### ISSUE TITLE
Update keeper-contracts diagram for v0.10

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/keeper-contracts#470]
The current [keeper-contract diagram](https://github.com/oceanprotocol/keeper-contracts/blob/release/v0.9/doc/files/Keeper-Contracts.png) needs to be updated with the new version `v0.9`.

**Comment by erwinkn** [comment]
The diagram being automatically generated, some of the calls indicated there are not accurate w/ regards to the code. Since the diagram is listed in the public documentation for the keeper-contracts, it would be good to indicate this clearly in order to avoid possible confusions.
