### ISSUE TITLE
Tokens never leave escrow?

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#516]
I am having a strange behaviour with the EscrowReward and fulfill of the condition:

Every time the fulfill gets called from `brizo` it fails:
https://kovan.etherscan.io/txs?a=0xaeded2ebc0C04160fFC3cA1d830827b92ceb17d5

The issue is always Out Of Gas as seen here:

https://kovan.etherscan.io/tx/0x63692ef4a3a029a20b98c0baed067dd7118c6f4fc1c72da41a35af89b47f2d3b

This leads to the case that tokens never leave escrow:

https://kovan.etherscan.io/address/0xaeded2ebc0C04160fFC3cA1d830827b92ceb17d5#tokentxns

I checked the other chains (like nile) and i can also see that tokens never leave escrow: https://submarine.dev-ocean.com/address/0xed4ef53376c6f103d2d7029d7e702e082767c6ff/transactions

**Comment by 0x3bfc** [comment]
@H34D please close it when you report it as a Brizo Issue 👍

**Comment by H34D** [comment]
closed in favour of https://github.com/oceanprotocol/brizo/issues/141
