### ISSUE TITLE
Refactor whitelisting conditions

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/keeper-contracts#532]
The flow below should describe the whitelisting condition design pattern:

![image](https://user-images.githubusercontent.com/5428661/60587658-4d0e9500-9d95-11e9-97f3-b03f2002e789.png)

In order to implement the whitelist condition we need the following contracts:
- `IList.so` a list interface which describes the required interface functions for the whitelist.
- `ListLibrary` implements the basic functionalities
- `SampleWhitelist.sol` this contract holds the data of the list and provides the required functionalities for the whitelist by using `ListLibrary.sol`.
- `WhitelistCondition` holds the `fulfill` function in which calls `list.has(item)` in order to call `super.fulfill` method and set the condition state to `Fulfilled`.

### Implementation details

The following example shows a working example:
```javascript
pragma solidity ^0.5.6;

interface IList {
    
    function add(
        bytes32 item    
    )
        external;
    function has(
        bytes32 item    
    )
        external
        view
        returns(bool);
    
    function hash(
        uint256 item    
    )
        external
        pure
        returns(bytes32);
    
}


contract MyList is IList {
    mapping(bytes32 => bool) list;
    
    
    function add(
        bytes32 item    
    )
        external
    {
        require(
            !list[item],
            'item already exists'
        );
        list[item] = true;
    }
    
    function has(
        bytes32 item
    ) 
        external
        view
        returns(bool)
    {
        return list[item];
    }
    
    function hash(
        uint256 item    
    )
        external
        pure
        returns(bytes32)
    {
        return keccak256(abi.encodePacked(item));
    }
}


contract myContract {
    
    IList list;
    
    constructor(address listAddress)
        public
    {
        list = IList(listAddress);
    }
    
    function isExist(
        bytes32 item
    )
        public
        view
        returns(bool)
    {
        return list.has(item);
    }
}
```

### Testing
![image](https://user-images.githubusercontent.com/5428661/60817414-e4ac2300-a19b-11e9-9547-3e54532b243b.png)

**Comment by diminator** [comment]
LGTM

**Comment by diminator** [comment]
You can mention that 
`IList` implements `list.has(item)`
