### ISSUE TITLE
Possibility of having DoS attack on Keeper Contracts/Network [Only for Common Marketplace]

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/keeper-contracts#547]
**Description**
The current deployment of Ocean Protocol `Pacific` allows anybody to get free Eth. This is just used to run the network and nothing to do with the data, as the publisher will get paid using ocean token. But from a Commons marketplace point of view, an adversary can flush the network with a huge number of transactions in which block the other healthy transaction to be mined. 

I am wondering what prevent anyone from running this attack. 

We have no control over:
- Number of Eth accounts and they are free
- Number of free/public assets
- Number of proposed transactions

So blocking any of them won't work!

**Proposal**
As @diminator suggested to have PoW on the client side in which you have to provide a proof every time you consume free asset. This might limit the DoS and at the same time it is simple for a good actor with a limited computing power to generate it. As a result this requires to include a new condition for it. 
It could be the `HashLockCondition` but still lacks  a lot of info regarding to how, and where the pre-image is calculated/stored

**Comment by H34D** [comment]
We reduced the amount of ETH from the faucet to 0.05 ETH on the `pacific` network.

**Comment by 0x3bfc** [comment]
@H34D Did we apply this to Pacific network ?
