### ISSUE TITLE
Java package for keeper-contracts packages bouncycastle/bcprov-jdk15on classes 

### ISSUE THREAD

**Issue by shark8me** [oceanprotocol/keeper-contracts#564]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [y ] I am running the latest version
- [ y] I checked the documentation and found no answer
- [ y] I checked to make sure that this issue has not already been filed
- [ y] I'm reporting the issue to the correct repository.

## Expected Behavior

Applications that use Squid will expect to include squid-java as a dependency in their pom.xml. Importing it should be successful.

## Current Behavior

If applications also have a dependency on bouncycastle's [bcprov-jdk15on](https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on) for other cryptographic functions, then the application does not load since it finds the same classes in two sources:

- keeper-contracts
- their dependency of bcprov-jdk15on.

## Failure Information (for bugs)

This fails while loading the classes (e.g. in a test).

```sh
Caused by: java.lang.SecurityException: class "org.bouncycastle.jcajce.provider.digest.SHA3$DigestSHA3"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1150)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:905)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1014)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

```

On querying keeper-contracts jar, bouncycastle classes are present:
```sh
k@tp:~/src/ocn/starfish-clj$ jar tvf ~/.m2/repository/com/oceanprotocol/keeper-contracts/0.10.3/keeper-contracts-0.10.3.jar |grep bouncy|head
     0 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/
     0 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/
  2905 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/ASN1ApplicationSpecific.class
   308 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/ASN1ApplicationSpecificParser.class
  3464 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/ASN1BitString.class
  2669 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/ASN1Boolean.class
    84 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/ASN1Choice.class
   155 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/ASN1Encodable.class
   874 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/ASN1EncodableVector.class
  2573 Thu Jun 20 14:51:14 MYT 2019 org/bouncycastle/asn1/ASN1Enumerated.class

```
The cause of the error is:

1. The JVM loads both bcprov-jdk15on and keeper-contracts jars
2. On encountering a class in keeper-contracts jar, it attempts to load it, and usually succeeds.
3. On attempting to load a different class (e.g. org.bouncycastle.jcajce.provider.digest.SHA3$DigestSHA3), it finds that this class is loaded from a (bcprov-jdk15on) jar that has a different signature than keeper-contracts. 
4. And thus exits with an error

### Possible Solution

Keeper-contracts jar should not include  bouncycastle classes. This can be fixed by modifying the pom.xml to exclude bouncycastle classes.

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: 0.10.3
* JDK: 11

**Comment by aaitor** [comment]
`org.bouncycastle:bcprov-jdk15on` is a dependency of `org.web3j:utils`. You can exclude any library you don't need from your application in the pom.xml. Example:

```
        <dependency>
            <groupId>com.oceanprotocol</groupId>
            <artifactId>keeper-contracts</artifactId>
            <version>${ocean.keeper.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15on</artifactId>
               </exclusion>
           </exclusions>
        </dependency>

```

**Comment by shark8me** [comment]
There is a difference between keeper-contracts having a dependency on `bouncycastle` or indeed any other package, and actually bundling those classes in the install bundle.

Libraries that are include keeper contracts as a dependency should expect to find classes from the keeper-contracts package, not other classes.

As things stand, all users/libraries that include both bouncycastle and keeper-contracts (not even keeper-contracts directly, but include squid-java), trip up on the issue, and are forced to examine all the jars in the classpath to look for the duplicate classes from bouncycastle. This is simply bad form, and for the lay user, quite difficult to find. 

It is much easier for keeper-contracts jar to simply exclude the offending classes from bouncycastle

**Comment by H34D** [comment]
This is a typical "dependency-hell" case. 

I proposed the issue: #638 to solve this and move the web3j reference to the consumer.

**Comment by 0x3bfc** [comment]
Java packages are no longer supported, please refer to the [rest-api](https://github.com/oceanprotocol/rest-api)

**Comment by shark8me** [comment]
The link to rest-api gives me a 404 error

**Comment by 0x3bfc** [comment]
It is private but will go public soon.

**Comment by trentmc** [comment]
Obsolete. Closing.
