### ISSUE TITLE
As a user I would like to be able to specify the duration or validity of a service agreement

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#586]
The use case would be:
"As a provider (data, compute, etc) I would like to specify the duration of a service agreement, for example a user purchasing an access service can consume this asset during 1 week."

**Comment by ShawkiS** [comment]
I suggest that: 
We add a variable called **duration** to the CreateAgreement method in the **AgreementStoreManager** contract and we check the duration parameter whenever there is a consume function for example: the **consumeService** function in Brizo we check this function at the beaning by getting the duration from the agreement id

**Comment by ssallam** [comment]
This is not bad, but it would be better if the implementation was completely on-chain such that the provider does not need to check for timeout or expiration, all the provider needs to do is to check whether or not a consumer address has valid access permission.
