### ISSUE TITLE
Direct Purchase

### ISSUE THREAD

**Issue by ilyabukalov** [oceanprotocol/keeper-contracts#642]
Hey @ilyabukalov thanks for contributing. What is this functionality for? Can you please describe what you want to achieve in an issue please? It looks like that this functionality can be deployed side by side to keeper contracts easily and does not necessarily has to go into its main functionality.

_Originally posted by @H34D in https://github.com/oceanprotocol/keeper-contracts/pull/641#issuecomment-536498117_

Exactly. The only thing which is attached to existing contracts is OceanToken contract. Its address should be passed into DirectPurchase constructor during deployment.
example of deployment scripts are here https://github.com/dex-Company/direct-purchase
The functionality of DirectPurchase itself is used directly from Starfish now but it could be part of squid as well and it could be separated PL. Thanks.

**Comment by H34D** [comment]
> Hey @ilyabukalov thanks for contributing. What is this functionality for? Can you please describe what you want to achieve in an issue please? It looks like that this functionality can be deployed side by side to keeper contracts easily and does not necessarily has to go into its main functionality.
> 
> _Originally posted by @H34D in [#641 (comment)](https://github.com/oceanprotocol/keeper-contracts/pull/641#issuecomment-536498117)_
> 
> Exactly. The only thing which is attached to existing contracts is OceanToken contract. Its address should be passed into DirectPurchase constructor during deployment.
> example of deployment scripts are here https://github.com/dex-Company/direct-purchase
> The functionality of DirectPurchase itself is used directly from Starfish now but it could be part of squid as well and it could be separated PL. Thanks.

Thanks for clarification. What exactly is this for?

**Comment by ilyabukalov** [comment]
https://github.com/dex-Company/direct-purchase repo is development+deployment scripts+docker container. And all these currently are part of dex/barge. But now we want to shift it to ocean/keeper to make it more transparent and clear. 
The functionality is simple - it just extends logging during transfer tokens, so we will be able to put extra information during payment. From user prospective it can be used when publisher and purchaser know each other and trust each other. They just want to transfer tokens directly with recording of extra identification information.
