### ISSUE TITLE
Multi-party commitments for the reward distribution

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/keeper-contracts#654]
## Problem Description
- The current service execution agreement is defined by two parties only. The commitment scheme is implicitly imbedded in the agreement where the buyer (consumer) creates agreement and the seller (provider) sends a consent by fulfilling conditions.
- A complex use case scenarios might require multiple parties (>2) such as consumer, provider broker commissions (ie. marketplaces), publishers, curators, network verifiers and etc. 
- Each commitment should include (`from, to, reward, DID, agreementId`)
- Supporting multi-party commitments, will leverage the agreement capabilities to accept more complex reward distribution for the same asset or bundled assets. 

## Requirements
The commitment scheme should be generic enough to preserve:
- `Integrity`: reward distribution MUST be the same off-chain and on-chain.
- `Consensus`: among all parties, it MUST reach a consensus prior to agreement execution.
- `Succinctness`: on-chain validation should have a fixed verification time and should be independent of the cost of off-chain proof generation.

Moreover it should NOT **_depend_** on the number of the actors in the system.

**Comment by ssallam** [comment]
* The asset owner is responsible for defining how the payment gets distributed
* Asset owner chooses a contract address of a payment distribution contract
* There is a default payment distribution contract that allows asset owner to specify the payment receivers along with their shares
* The payment distribution scheme is associated with the asset id and can only be set and updated by the asset owner
* The reward (payment) condition in an SEA sends the payment to the payment distribution contract specified above

**Comment by alexcos20** [comment]
What about the following:

1) update OEP/8 to reflect commision schema
The commision schema should be an array (or unidimensional arrays in solidity), with the following  attributes:
       -  address   - the address that will receive the reward
       -  type     - if it's 0 then quantity is expressed in percent of the original amount.  If it's 1, then it's a fixed amount
       -  quantity  - either fixed amount or percent, depending on type

2) add the commision scheme in the DID Registry, when creating new DID. The method is optional, so we can have backward compatibility or have assests without the commision scheme

3) update every Escrow contract to get the commision schema from DIDRegistry and act accordingly, IF the schema EXISTS, do the math and the leftover is sent to the DID owner. 

4) update squids to allow the commision schema as an optional parameter

Example:        

 Alice wants to publish a new dataset in Bob's marketplace using Carlos's channel .  Bob's is going to charge 10% fees, and Carlos will charge 1 token.
The commision scheme will look like:
    -  address[0]='BobETHaddr' , address[1]='CarlosETHaddr'
    -  type[0]=0, type[1]=1
    - quantity[0]=10, quantity[1]=1

The escrow reward will calculate the following:
         Bob's reward= ContractAmount*10/100
         Carlos's reward=1
        Alice's reward=ContractAmount-Bob's reward - Carlo's reward.

If the schema DOES NOT EXISTS, then Alice's reward=ContractAmount

**Comment by devpramoth** [comment]
![image](https://user-images.githubusercontent.com/41467505/73767003-24111100-4777-11ea-871d-00d56614db9d.png)
