### ISSUE TITLE
Moving the event AgreementActorAdded to AgreementStoreManager

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/keeper-contracts#692]
Based on the feedback from @ssallam the expected event is not found in the ABI, and this causes an error when trying to grab the event:

```
web3.exceptions.MismatchedABI: ("The event 'AgreementActorAdded' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')
```

**Comment by ssallam** [comment]
This is a blocker, python tests fail because this even is missing from the abi definition.
