### ISSUE TITLE
Add convenient functions to retrieve actor types.

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/keeper-contracts#699]
It should be easy to get the list of actor types for an agreement template. Currently to do this, we have to get the template actor ids, the get the actor type for each id.

New function:
* `getActorTypes`
* argument: `templateId`
* return: list of actor types (strings)

**Comment by 0x3bfc** [comment]
You can get actor types for a template as shown below:
https://github.com/oceanprotocol/keeper-contracts/blob/67305339f4b12c7a51a521fbbb0fb39863c79bbc/contracts/templates/TemplateStoreManager.sol#L221

**Comment by ssallam** [comment]
Couldn't complete this task because solidity does not support return of list of strings.
