### ISSUE TITLE
Check keeper-contracts on all networks

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/keeper-contracts#729]

**Comment by 0x3bfc** [comment]
@alexcos20 can you add a description, what should be fixed/done to close this issue ? Thanks

**Comment by kremalicious** [comment]
I think this was meant for checking if latest keeper-contracts are also rolled out on Duero, cause we were running into issues there

**Comment by 0x3bfc** [comment]
I already keep updating the logs folder in the `Atlantic repo` for network approval. If there is an issue with the upgrade, please open an issue on Atlantic. 

Regarding `Duero` network, I'll check it out.

**Comment by alexcos20** [comment]
Can we add getVersion methods for our contracts?  It will return a simple but usefull string
