### ISSUE TITLE
Discuss/change ABI/Address handling

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#73]

**Comment by eruizgar91** [comment]
The current approach in the provider is that you have to fill this 3 config params when you are going to start to run the contracts:
`market.address = 0x2612Af3A521c2df9EAF28422Ca335b04AdF3ac66
auth.address = 0x0E696947A06550DEf604e82C26fd9E493e576337
token.address = 0xCfEB869F69431e42cdB54A4F4f105C19C080A601`
It is working well in local, we should try to run using the contracts deployed in a external network.

**Comment by H34D** [comment]
> The current approach in the provider is that you have to fill this 3 config params when you are going to start to run the contracts:

where do you load the ABI's from?

**Comment by eruizgar91** [comment]
We are using this abi files https://pypi.org/project/keeper-contracts/ It is supposed that every time that we do a deployment in kovan or another network we should release this library.

**Comment by H34D** [comment]
the addresses are in those files. You only need to load them.

```json
{
  "abi": [
  ],
  "bytecode": "0x0asd",
  "address": "0x1A90bDe75809Ca8CE5A8a5288a7D8Ab734663c7d"
}
```

**Comment by H34D** [comment]
https://github.com/dharmaprotocol/charta/tree/master/scripts

**Comment by H34D** [comment]
i added some context to the status quo: 

https://github.com/oceanprotocol/dev-ocean/blob/d7eab383e2266e327d7667bcdbef08653950c332/doc/architecture/contracts.md

**Comment by H34D** [comment]
obsolete with zeppelin os
